// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCARouIvqYeAnv5ni1sh1P4Wx9cEpDgVJU',
    appId: '1:99145683637:web:f9b7f2369233a2f70e64fc',
    messagingSenderId: '99145683637',
    projectId: 'device-streaming-1bb9e6dd',
    authDomain: 'device-streaming-1bb9e6dd.firebaseapp.com',
    storageBucket: 'device-streaming-1bb9e6dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtRigq-ie17e0zWGH8plXTakDOTjflI6E',
    appId: '1:99145683637:android:03faace3f1a8af320e64fc',
    messagingSenderId: '99145683637',
    projectId: 'device-streaming-1bb9e6dd',
    storageBucket: 'device-streaming-1bb9e6dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwRElD5RfOtEI3_KG2gxIM51If7W34TI8',
    appId: '1:99145683637:ios:7e8895642795310f0e64fc',
    messagingSenderId: '99145683637',
    projectId: 'device-streaming-1bb9e6dd',
    storageBucket: 'device-streaming-1bb9e6dd.firebasestorage.app',
    iosBundleId: 'com.vishal.odtrackacademia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwRElD5RfOtEI3_KG2gxIM51If7W34TI8',
    appId: '1:99145683637:ios:7e8895642795310f0e64fc',
    messagingSenderId: '99145683637',
    projectId: 'device-streaming-1bb9e6dd',
    storageBucket: 'device-streaming-1bb9e6dd.firebasestorage.app',
    iosBundleId: 'com.vishal.odtrackacademia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCARouIvqYeAnv5ni1sh1P4Wx9cEpDgVJU',
    appId: '1:99145683637:web:c766720d6e35804c0e64fc',
    messagingSenderId: '99145683637',
    projectId: 'device-streaming-1bb9e6dd',
    authDomain: 'device-streaming-1bb9e6dd.firebaseapp.com',
    storageBucket: 'device-streaming-1bb9e6dd.firebasestorage.app',
  );

}