"""add_staff_id_to_od_requests

Revision ID: 4d9bab6103cb
Revises: 71cab71d9bc5
Create Date: 2026-03-11 13:19:33.706007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9bab6103cb'
down_revision: Union[str, Sequence[str], None] = '71cab71d9bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('od_requests', sa.Column('staff_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'od_requests', 'users', ['staff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'od_requests', type_='foreignkey')
    op.drop_column('od_requests', 'staff_id')
    # ### end Alembic commands ###
