"""add student academic fields

Revision ID: 71cab71d9bc5
Revises: 0f3216c7b0f4
Create Date: 2026-03-10 05:41:48.329123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71cab71d9bc5'
down_revision: Union[str, Sequence[str], None] = '0f3216c7b0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('register_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('year', sa.String(), nullable=True))
    op.add_column('users', sa.Column('section', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_register_number'), 'users', ['register_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_register_number'), table_name='users')
    op.drop_column('users', 'section')
    op.drop_column('users', 'year')
    op.drop_column('users', 'register_number')
    # ### end Alembic commands ###
